### ISSUE TITLE
jdk JRE version compatible

### ISSUE THREAD

**Issue by kimsijin33** [securedimensions/authzforce-ce-geoxacml3#3]
Could I use jdk, JRE version 21?

My environment like a below.

$ java --version
openjdk 21.0.3 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 21.0.3+9-Ubuntu-1ubuntu1, mixed mode, sharing)

**Comment by securedimensions** [comment]
Such an upgrade requires that the Authzforce software stack also supports Java 21. But, it looks like that their latest version is Java 17...

So, I am afraid Java 21 is not possible right now.
